name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: msbuild /t:restore
    - name: Build
      run: msbuild /verbosity:d
